from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / 'data'
PROFILES_DIR = DATA_DIR / 'profiles'
EVENTS_DIR = DATA_DIR / 'events'

class Config:
    CAMERA_INDEX = 0
    WINDOW_NAME = 'AI SYSTEM PRO'
    DASHBOARD_PORT = 5070
    OPEN_BROWSER = True
    MAX_EVENTS = 500
    EVENT_COOLDOWN_SEC = 1.2
    POSITION_CHANGE_PX = 20.0
    COLOR_CHANGE_THRESHOLD = 24.0
    VISUAL_CHANGE_THRESHOLD = 16.0
    PHONE_ON_BRIGHTNESS = 65.0
    PHONE_CHANGE_THRESHOLD = 12.0
    BLINK_THRESHOLD = 0.20
    BLINK_CONSEC_FRAMES = 2
    SELF_FACE_THRESHOLD = 0.84
    ORB_FEATURES = 700
    TEMPLATE_SCALES = [0.6, 0.8, 1.0, 1.2]
    TEMPLATE_MATCH_THRESHOLD = 0.57
    TEMPLATE_MAX_SAMPLES = 4
    TEMPLATE_MIN_SIDE = 24
    MATCH_SCORE_THRESHOLD = 0.62
    ORB_MATCH_THRESHOLD = 0.18
    ADAPTIVE_MIN_MATCH_SCORE = 0.38
    ADAPTIVE_MIN_ORB_SCORE = 0.05
    ADAPTIVE_MIN_IDENTITY_SCORE = 0.52
    ADAPTIVE_MULTI_SAMPLE_IDENTITY_SCORE = 0.58
    ADAPTIVE_MULTI_SAMPLE_SUPPORT = 2
    ADAPTIVE_GRACE_FRAMES = 10
    APPEARANCE_MSE_LIMIT = 72.0
    COLOR_DISTANCE_LIMIT = 90.0
    MAX_SAMPLES_PER_PROFILE = 32
    DETECTOR_MODEL = 'yolov8s-world.pt'
    DETECTOR_CONFIDENCE = 0.18
    DETECTOR_IMAGE_SIZE = 640
    DETECTOR_MAX_RESULTS = 24
    DETECTOR_FRAME_STRIDE = 3
    MISSING_EVENT_REPEAT_SEC = 20.0
    BEEP_ALIAS = 'SystemAsterisk'
